# Generated by Django 3.1.4 on 2021-01-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=15)),
                ('RentedBike', models.FloatField(null=True)),
                ('Hour', models.IntegerField(default=0)),
                ('Temperature', models.FloatField(default=0.0)),
                ('Humidity', models.IntegerField(default=0)),
                ('Wind', models.FloatField(default=0.0)),
                ('Visibility', models.IntegerField(default=0)),
                ('DewPointTemperature', models.FloatField(default=0.0)),
                ('SolarRadiation', models.FloatField(default=0.0)),
                ('Rainfall', models.FloatField(default=0.0)),
                ('Snowfall', models.FloatField(default=0.0)),
                ('Season', models.CharField(choices=[('Autumn', 'Autumn'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Winter', 'Winter')], max_length=15)),
                ('Holiday', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
